# Note: You can use any Debian/Ubuntu based image you want.
FROM mcr.microsoft.com/devcontainers/base:bookworm

ENV XDG_CACHE_HOME="/workspace/local/tmp/node-22/cache" \
    XDG_CONFIG_HOME="/workspace/local/tmp/node-22/config" \
    NPM_CONFIG_CACHE="/workspace/local/tmp/node-22/cache/npm" \
    PIP_CACHE_DIR="/workspace/local/tmp/python-3.10/cache" \
    POETRY_CACHE_DIR="/workspace/local/tmp/python-3.10/cache" \
    NODE_OPTIONS="--max-old-space-size=4096"
